/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.clipper_gui;

import com.jakubwawak.clipper.Classifier;
import com.jakubwawak.clipper.Snippet;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *Object for creating window to setting category
 * @author jakubwawak
 */
public class category_window extends javax.swing.JDialog {

    /**
     * Creates new form category_window
     */
    Snippet actual_snippet;
    public category_window(javax.swing.JDialog parent, boolean modal,Snippet to_edit) {
        super(parent, modal);
        actual_snippet = to_edit;
        this.setLocationRelativeTo(parent);
        initComponents();
        getContentPane().setBackground(Color.blue);
        load_list();
        setting_select();
        setVisible(true);
    }
    
    /**
     * Function for loading list
     */
    void load_list(){
        DefaultListModel dlm = new DefaultListModel();
        Classifier c = new Classifier();
        dlm.addAll(Arrays.asList(c.codes));
        list_category.setModel(dlm);
    }
    
    /**
     * Function for setting selection on list object
     */
    void setting_select(){
        for(String data : list_category.getSelectedValuesList()){
            if ( data.equals(actual_snippet.classifier.CLASS_CODE) ){
                list_category.setSelectedIndex(list_category.getSelectedValuesList().indexOf(data));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_category = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        list_category.setBackground(new java.awt.Color(0, 0, 0));
        list_category.setForeground(new java.awt.Color(102, 153, 255));
        list_category.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_categoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_category);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_categoryMouseClicked
        actual_snippet.classifier.CLASS_CODE = list_category.getSelectedValue();
        dispose();
    }//GEN-LAST:event_list_categoryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_category;
    // End of variables declaration//GEN-END:variables
}
