/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.clipper_gui;

import com.jakubwawak.clipper.Snippet;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *Object for creating details window
 * @author jakubwawak
 */
public class details_window extends javax.swing.JDialog {

    /**
     * Creates new form details_window
     */
    int combobox_selected;
    Snippet session_snippet;
    
    String textarea_state1,textarea_state2;
    
    public details_window(java.awt.Frame parent, boolean modal,Snippet to_show) {
        super(parent, modal);
        session_snippet = to_show;
        this.setUndecorated(true);
        initComponents();
        combobox_selected = 0;
        getContentPane().setBackground(Color.GRAY);
        load_window();
        this.setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * Function for loading window components
     */
    void load_window(){
        textarea_data.setText(session_snippet.raw_data);
        textarea_data.setEditable(false);
        textarea_state2 = session_snippet.raw_data;
        label_category.setText(session_snippet.classifier.CLASS_CODE);
        if ( session_snippet.note.equals("") ){
            textarea_notes.setText("Notes here...");
        }
        else{
            textarea_notes.setText(session_snippet.note);
        }
        textarea_state1 = textarea_notes.getText();
    }
    
    /**
     * Function for closing window
     */
    void close_action(){
        if ( !textarea_state1.equals(textarea_notes.getText()) ){
            if ( !textarea_notes.getText().contains("Notes here...")){
                session_snippet.note = textarea_notes.getText();
            }
        }
        if ( !textarea_data.getText().equals(textarea_state2) ){
            session_snippet.raw_data = textarea_data.getText();
        }
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_data = new javax.swing.JTextArea();
        combobox_action = new javax.swing.JComboBox<>();
        label_category = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea_notes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        textarea_data.setBackground(java.awt.Color.darkGray);
        textarea_data.setColumns(20);
        textarea_data.setForeground(new java.awt.Color(255, 255, 0));
        textarea_data.setRows(5);
        textarea_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textarea_dataKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(textarea_data);

        combobox_action.setBackground(java.awt.Color.gray);
        combobox_action.setForeground(new java.awt.Color(0, 0, 0));
        combobox_action.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actions...", "Change category", "Edit data", "Send by email", "Copy snippet", "Close" }));
        combobox_action.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combobox_actionMouseClicked(evt);
            }
        });
        combobox_action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_actionActionPerformed(evt);
            }
        });
        combobox_action.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combobox_actionKeyPressed(evt);
            }
        });

        label_category.setForeground(new java.awt.Color(255, 255, 0));
        label_category.setText("CATEGORY");

        textarea_notes.setBackground(new java.awt.Color(153, 153, 153));
        textarea_notes.setColumns(20);
        textarea_notes.setForeground(new java.awt.Color(255, 255, 0));
        textarea_notes.setRows(5);
        textarea_notes.setText("Notes here...");
        textarea_notes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textarea_notesKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(textarea_notes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_category, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox_action, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_action, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(label_category))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobox_actionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobox_actionMouseClicked
        combobox_selected = combobox_action.getSelectedIndex();
        System.out.println("Combobox index selected: "+combobox_selected);
        /**
         *  0 Actions...
            1 Change category
            2 Edit data
            3 Send by email
            4 Copy snippet
            5 Remove
            6 Close
         */
        
        switch(combobox_selected){
            // change category
            case 1:
                new category_window(this,true,session_snippet);
                break;
            // copy snippet
            case 4:
                StringSelection selection = new StringSelection(session_snippet.snippet_clip());
                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                clipboard.setContents(selection, selection);
                break;
            // 6 Close
            case 6:
                close_action();
                break;
            // default operation
            default:
                break;
        }
        //combobox_action.
    }//GEN-LAST:event_combobox_actionMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE){
            close_action();
        }
    }//GEN-LAST:event_formKeyPressed

    private void textarea_dataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textarea_dataKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE){
            close_action();
        }
    }//GEN-LAST:event_textarea_dataKeyPressed

    private void combobox_actionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combobox_actionKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE){
            close_action();
        }
    }//GEN-LAST:event_combobox_actionKeyPressed

    private void textarea_notesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textarea_notesKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE){
            close_action();
        }
    }//GEN-LAST:event_textarea_notesKeyPressed

    private void combobox_actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_actionActionPerformed
        /**
         *  0 Actions...
            1 Change category
            2 Edit data +
            3 Send by email
            4 Copy snippet +
            5 Close
         */
        switch(combobox_action.getSelectedIndex()){
            // close
            case 5:
                close_action();
                break;
            // edit data
            case 2:
                textarea_data.setEditable(true);
                break;
            // copy snippet
            case 4:
                StringSelection selection = new StringSelection(session_snippet.snippet_clip());
                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                clipboard.setContents(selection, selection);
                break;
            default:
                close_action();
                break;
        }
    }//GEN-LAST:event_combobox_actionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox_action;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_category;
    private javax.swing.JTextArea textarea_data;
    private javax.swing.JTextArea textarea_notes;
    // End of variables declaration//GEN-END:variables
}
